- name: remove existing directory
  # tags: 
  # - deployment
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}" # backend folder is /app, frontend /usr/share/nginx/html
    state: absent

- name: create app directory
  # tags: 
  # - deployment
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}" # backend folder is /app, frontend /usr/share/nginx/html
    state: directory

- name: download app code
  # tags: 
  # - deployment
  ansible.builtin.git:
    repo: "https://github.com/BhavyaAudisri/expense-backend-code.git"
    clone : no
    dest: /tmp/backend.zip

- name: unzip backend code
  ansible.builtin.unarchive:
    src: /tmp/backend.zip
    dest: "{{ APP_LOCATION }}"
    remote_src: yes