- name: remove existing directory
  # tags: 
  # - deployment
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}" # backend folder is /app, frontend /usr/share/nginx/html
    state: absent

- name: create app directory
  # tags: 
  # - deployment
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}" # backend folder is /app, frontend /usr/share/nginx/html
    state: directory

- name: download app code
  # tags: 
  # - deployment
  ansible.builtin.get_url:
   # repo: "https://github.com/BhavyaAudisri/expense-{{ COMPONENT }}-code.git"
    url: "https://github.com/BhavyaAudisri/expense-{{ COMPONENT }}-code/blob/main/expense-{{ COMPONENT }}-v2.zip" 
    dest : /tmp/backend.zip

# - name: unzip backend code
#   ansible.builtin.unarchive:
#     src: /tmp/backend.zip
#     dest: "{{ APP_LOCATION }}"
#     remote_src: yes

- name: unzip backend code from git
  ansible.builtin.shell: 
    cmd: unzip /tmp/backend.zip
    remote_src: yes